# Generated by Django 4.0.1 on 2022-01-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='post',
            name='upddated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
