# Generated by Django 4.0.1 on 2022-01-23 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_date_post_created_at_post_upddated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='upddated_at',
            new_name='updated_at',
        ),
    ]
